# Generated by Django 4.0.1 on 2022-02-01 12:32

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_myusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.CharField(max_length=50, verbose_name=django.forms.fields.EmailField),
        ),
    ]
