# Generated by Django 4.0.1 on 2022-02-02 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_alter_myusers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, verbose_name=django.forms.fields.EmailField)),
                ('intake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.intake')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.track')),
            ],
        ),
    ]
