# Generated by Django 4.0.1 on 2022-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_intake_track_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
